--------------------------------------------------------
--  DDL for Trigger BI_BOOKSCATEGORYDET_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_BOOKSCATEGORYDET_TRG" 
BEFORE INSERT ON BOOKSCATEGORYDET 
FOR EACH ROW 
     WHEN (new.BOOKCAT_ID IS NULL) BEGIN 
  :new.BOOKCAT_ID := BOOKSCATEGORYDET_SEQ.NEXTVAL; 
END; 
 

/
ALTER TRIGGER "INSTITUTE"."BI_BOOKSCATEGORYDET_TRG" ENABLE;
