--------------------------------------------------------
--  DDL for Trigger BI_EMAILS_ATTACHMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_EMAILS_ATTACHMENTS_TRG" 
BEFORE INSERT ON EMAIL_ATTACHMENTS 
FOR EACH ROW 
    WHEN (new.EMAIL_ATACH_ID IS NULL) BEGIN 
  :new.EMAIL_ATACH_ID := EMAIL_ATTACHMENTS_SEQ.NEXTVAL; 
END; 
 

/
ALTER TRIGGER "INSTITUTE"."BI_EMAILS_ATTACHMENTS_TRG" ENABLE;
