--------------------------------------------------------
--  DDL for Trigger BI_FEES_STRUCTURE_YEARLY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_FEES_STRUCTURE_YEARLY_TRG" 
BEFORE INSERT ON FEES_STRUCTURE_YEARLY 
FOR EACH ROW 
      WHEN (new.STRUCTURE_ID IS NULL) BEGIN 
  :new.STRUCTURE_ID :=FEES_STRUCTURE_YEARLY_SEQ.NEXTVAL; 
END; 
 

/
ALTER TRIGGER "INSTITUTE"."BI_FEES_STRUCTURE_YEARLY_TRG" ENABLE;
