--------------------------------------------------------
--  DDL for Trigger BI_HOSTEL_FEES_STRUCTURE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_HOSTEL_FEES_STRUCTURE_TRG" 
BEFORE INSERT ON HOSTEL_FEES_STRUCTURE 
FOR EACH ROW 
     WHEN (new.FEE_STRU_ID IS NULL) BEGIN 
  :new.FEE_STRU_ID := HOSTEL_FEES_STRUCTURE_SEQ.NEXTVAL; 
END; 
 

/
ALTER TRIGGER "INSTITUTE"."BI_HOSTEL_FEES_STRUCTURE_TRG" ENABLE;
