--------------------------------------------------------
--  DDL for Trigger BI_HOSTEL_ROOM_ASSIGN_DET_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_HOSTEL_ROOM_ASSIGN_DET_TRG" 
BEFORE INSERT ON HOSTEL_ROOM_ASSIGN_DET 
FOR EACH ROW 
     WHEN (new.ROOM_ASSIGN_ID IS NULL) BEGIN 
  :new.ROOM_ASSIGN_ID := HOSTEL_ROOM_ASSIGN_DET_SEQ.NEXTVAL; 
END; 
 

/
ALTER TRIGGER "INSTITUTE"."BI_HOSTEL_ROOM_ASSIGN_DET_TRG" ENABLE;
