--------------------------------------------------------
--  DDL for Trigger BI_SAMPLE_ADM_APPL_MST_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INSTITUTE"."BI_SAMPLE_ADM_APPL_MST_TRG" 
BEFORE INSERT ON SAMPLE_ADMISSION_APPLICATION 
FOR EACH ROW 
     WHEN (new.ADM_APPL_ID IS NULL) BEGIN 
  :new.ADM_APPL_ID := SAMPLE_ADMISSION_SEQ.NEXTVAL; 
END;

/
ALTER TRIGGER "INSTITUTE"."BI_SAMPLE_ADM_APPL_MST_TRG" ENABLE;
