--------------------------------------------------------
--  DDL for Sequence BOOKSCATEGORYDET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INSTITUTE"."BOOKSCATEGORYDET_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
