--------------------------------------------------------
--  DDL for Sequence HOSTEL_FEES_STRUCTURE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INSTITUTE"."HOSTEL_FEES_STRUCTURE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
