--------------------------------------------------------
--  DDL for Sequence STUDENT_LEAVE_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INSTITUTE"."STUDENT_LEAVE_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 43 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
