--------------------------------------------------------
--  Ref Constraints for Table HEALTH_REPORT
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" ADD CONSTRAINT "HEALTH_REPORT_DISEASE_MST_FK" FOREIGN KEY ("DISEASE_MAST_ID")
	  REFERENCES "INSTITUTE"."DISEASE_MST" ("DISEASE_MAST_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" ADD CONSTRAINT "HEALTH_REPORT_STUDENTS_DET_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "INSTITUTE"."STUDENTS_DET" ("STUDENT_ID") ENABLE;
