--------------------------------------------------------
--  Ref Constraints for Table PARENTS_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."PARENTS_DET" ADD CONSTRAINT "PARENTS_DET_INST_MST_FK" FOREIGN KEY ("INSTITUTE_ID")
	  REFERENCES "INSTITUTE"."INSTITUTE_MST" ("INSTITUTE_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."PARENTS_DET" ADD CONSTRAINT "PARENTS_DET_USERS_MST_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "INSTITUTE"."USERS_MST" ("USER_ID") ENABLE;
