--------------------------------------------------------
--  Ref Constraints for Table ROUTE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."ROUTE_MST" ADD CONSTRAINT "ROUTE_MST_INSTITUTE_MST_FK" FOREIGN KEY ("INSTITUTE_ID")
	  REFERENCES "INSTITUTE"."INSTITUTE_MST" ("INSTITUTE_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."ROUTE_MST" ADD CONSTRAINT "ROUTE_MST_VEHICAL_MST_FK" FOREIGN KEY ("VEHICAL_ID")
	  REFERENCES "INSTITUTE"."VEHICAL_MST" ("VEHICAL_ID") ENABLE;
