--------------------------------------------------------
--  Ref Constraints for Table STUDENT_FEES_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STUDENT_FEES_DET" ADD CONSTRAINT "STUD_FEES_DET_AC_YEAR_MST_FK" FOREIGN KEY ("AC_YEAR_ID")
	  REFERENCES "INSTITUTE"."ACADEMIC_YEAR_MST" ("AC_YEAR_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."STUDENT_FEES_DET" ADD CONSTRAINT "STUD_FEES_DET_INST_MST_FK" FOREIGN KEY ("INSTITUTE_ID")
	  REFERENCES "INSTITUTE"."INSTITUTE_MST" ("INSTITUTE_ID") ENABLE;
