--------------------------------------------------------
--  Ref Constraints for Table STUDENTS_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STUDENTS_DET" ADD CONSTRAINT "STUDENTS_DET_INSTITUTE_MST_FK" FOREIGN KEY ("INSTITUTE_ID")
	  REFERENCES "INSTITUTE"."INSTITUTE_MST" ("INSTITUTE_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."STUDENTS_DET" ADD CONSTRAINT "STUDENTS_DET_USERS_MST_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "INSTITUTE"."USERS_MST" ("USER_ID") ENABLE;
