--------------------------------------------------------
--  Ref Constraints for Table SUBJECT_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."SUBJECT_MST" ADD CONSTRAINT "SUBJECT_MST_SEMESTER_MST_FK" FOREIGN KEY ("SEM_ID")
	  REFERENCES "INSTITUTE"."SEMESTER_MST" ("SEM_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."SUBJECT_MST" ADD CONSTRAINT "SUBJECT_MST_STANDARD_MST_FK" FOREIGN KEY ("STD_ID")
	  REFERENCES "INSTITUTE"."STANDARD_MST" ("STD_ID") ENABLE;
