--------------------------------------------------------
--  Ref Constraints for Table TIMETABLE
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_ASSIGN_SUB_DET_FK" FOREIGN KEY ("ASSIGN_ID")
	  REFERENCES "INSTITUTE"."ASSIGN_SUB_DET" ("ASSIGN_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_INSTITUTE_MST_FK" FOREIGN KEY ("INSTITUTE_ID")
	  REFERENCES "INSTITUTE"."INSTITUTE_MST" ("INSTITUTE_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_TIME_MST_FK" FOREIGN KEY ("TIME_ID")
	  REFERENCES "INSTITUTE"."TIME_MST" ("TIME_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."TIMETABLE" ADD CONSTRAINT "TIMETBLMST_TIMETBL_MST_FK" FOREIGN KEY ("TIMEMST_ID")
	  REFERENCES "INSTITUTE"."TIMETABLE_MST" ("TIMEMST_ID") ENABLE;
