--------------------------------------------------------
--  Ref Constraints for Table TRANSPORT_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" ADD CONSTRAINT "TRANSPORT_DET_POINTS_MST_FK" FOREIGN KEY ("POINT_ID")
	  REFERENCES "INSTITUTE"."POINTS_MST" ("POINT_ID") ENABLE;
  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" ADD CONSTRAINT "TRANSPORT_DET_ROUTE_MST_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "INSTITUTE"."STUDENTS_DET" ("STUDENT_ID") ENABLE;
