--------------------------------------------------------
--  DDL for Package Body UT_EMS_TEST_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_EMS_TEST_UTIL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 13:10:47

   --
   -- test upload_questions_to_db
   --
procedure upload_questions_to_db is
    l_actual_inst   integer;
    l_expected_inst integer := 36;
    l_actual_yr   integer;
    l_expected_yr integer := 36;
begin
    -- arrange
      
    -- act
    -- ems_test_util.upload_questions_to_db;
    SELECT INSTITUTE_ID INTO l_actual_inst FROM INSTITUTE_MST WHERE INST_CODE = 'DRAVIJ';
    SELECT AC_YEAR_ID INTO l_actual_yr FROM ACADEMIC_YEAR_MST WHERE INSTITUTE_ID = l_actual_inst;
    
    -- assert
    ut.expect(36).to_equal(l_expected_inst);
    ut.expect(36).to_equal(l_expected_yr);
end upload_questions_to_db;

--
-- test insert_correct_ans
--
procedure insert_correct_ans is
    l_actual_inst   integer;
    l_expected_inst integer := 36;
begin
    -- arrange

    -- act
    -- ems_test_util.insert_correct_ans;
    SELECT INSTITUTE_ID INTO l_actual_inst FROM INSTITUTE_MST WHERE INST_CODE = 'DRAVIJ';
    
    -- assert
    ut.expect(36).to_equal(l_expected_inst);
end insert_correct_ans;

end ut_EMS_TEST_UTIL;

/
