--------------------------------------------------------
--  DDL for Package Body UT_EMS_PROMOTION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_EMS_PROMOTION" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 13:11:33

--
-- test class_settings
--
procedure class_settings is
    l_actual_inst   integer;
    l_expected_inst integer := 36;
    l_actual_yr   integer;
    l_expected_yr integer := 36;
    l_actual_newyr integer;
    l_expected_newyr integer := 37;
    l_div_list varchar2(50);
    l_actual_div ut_varchar2_list;
    l_expected_div ut_varchar2_list;
begin
    -- arrange
    l_expected_div := ut_varchar2_list('57,58,59,60,61,62');
    -- act
    -- ems_promotion.class_settings;
    SELECT INSTITUTE_ID INTO l_actual_inst FROM INSTITUTE_MST WHERE INST_CODE = 'DRAVIJ';
    SELECT AC_YEAR_ID INTO l_actual_yr FROM ACADEMIC_YEAR_MST WHERE INSTITUTE_ID = l_actual_inst;
    SELECT LISTAGG(DIVISION_ID,',') WITHIN GROUP (ORDER BY DIVISION_ID) INTO l_div_list  FROM DIVISION_MST WHERE MED_ID = 54;
    l_actual_div := ut_varchar2_list(l_div_list);
    -- assert
    ut.expect(36).to_equal(l_expected_inst);
    ut.expect(36).to_equal(l_expected_yr);
    ut.expect(37).to_equal(l_expected_newyr);
    ut.expect( anydata.convertCollection(l_actual_div)).to_contain( anydata.convertCollection(l_expected_div));
    --ut.expect(l_actual_div).to_contain(l_expected_div);    
end class_settings;

--
-- test subject_settings
--
procedure subject_settings is
    l_actual_inst   integer;
    l_expected_inst integer := 36;
    l_actual_yr   integer;
    l_expected_yr integer := 36;
    l_actual_newyr integer;
    l_expected_newyr integer := 37;
    l_sub_list varchar2(50);
    l_actual_sub ut_varchar2_list;
    l_expected_sub ut_varchar2_list;
begin
    -- arrange
    l_expected_sub := ut_varchar2_list('93,94,95,96,97,98,99');
    -- act
    -- ems_promotion.subject_settings;
    SELECT INSTITUTE_ID INTO l_actual_inst FROM INSTITUTE_MST WHERE INST_CODE = 'DRAVIJ';
    SELECT AC_YEAR_ID INTO l_actual_yr FROM ACADEMIC_YEAR_MST WHERE INSTITUTE_ID = l_actual_inst;
    SELECT LISTAGG(SUB_ID,',') WITHIN GROUP (ORDER BY SUB_ID) INTO l_sub_list FROM SUBJECT_MST WHERE STD_ID = 40;
    l_actual_sub := ut_varchar2_list(l_sub_list);
    -- assert
    ut.expect(36).to_equal(l_expected_inst);
    ut.expect(36).to_equal(l_expected_yr);
    ut.expect(37).to_equal(l_expected_newyr);
    ut.expect( anydata.convertCollection(l_actual_sub)).to_contain( anydata.convertCollection(l_expected_sub));
    
end subject_settings;

end ut_EMS_PROMOTION;

/
