--------------------------------------------------------
--  DDL for Package Body UT_OMS_USER_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_OMS_USER_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 14:59:03

   --
   -- test get_usertypecode_fromusername
   --
   procedure get_usertypecode_fromusername is
      l_actual   varchar2(50);
      l_expected varchar2(50);
   begin
      -- arrange

      -- act
      -- oms_user_utl.get_usertypecode_fromusername;
    l_actual := OMS_USER_UTL.get_usertypecode_fromusername('ADMIN');
      -- assert
      ut.expect(l_actual).to_equal('ADM');
   end get_usertypecode_fromusername;

   --
   -- test get_compid_fromusername
   --
   procedure get_compid_fromusername is
      l_actual   integer := 0;
      l_expected integer := 1;
   begin
      -- arrange

      -- act
      -- oms_user_utl.get_compid_fromusername;
    l_actual := OMS_USER_UTL.get_compid_fromusername('ADMIN');
      -- assert
      ut.expect(l_actual).to_equal(1);
   end get_compid_fromusername;

   --
   -- test get_userid_fromusername
   --
   procedure get_userid_fromusername is
      l_actual   integer := 0;
      l_expected integer := 1;
   begin
      -- arrange

      -- act
      -- oms_user_utl.get_userid_fromusername;
    l_actual := OMS_USER_UTL.get_userid_fromusername('ADMIN');
      -- assert
      ut.expect(l_actual).to_equal(4);
   end get_userid_fromusername;

   --
   -- test create_user_types
   --
   procedure create_user_types is
      l_actual   integer := 1;
      l_expected integer := 1;
   begin
      -- arrange

      -- act
      -- oms_user_utl.create_user_types;

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end create_user_types;

end UT_OMS_USER_UTL;

/
