--------------------------------------------------------
--  DDL for Package Body UT_OMS_PROJECT_MANAGE_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_OMS_PROJECT_MANAGE_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 15:46:42

   --
   -- test assign_ticket
   --
   procedure assign_ticket is
      l_actual   integer := 1;
      l_expected integer := 1;
   begin
      -- arrange

      -- act
      -- oms_project_manage_utl.assign_ticket;

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end assign_ticket;

   --
   -- test delete_ticket
   --
procedure delete_ticket is
    c_actual sys_refcursor;
    c_expected sys_refcursor;
begin
      -- arrange

      -- act
      -- oms_project_manage_utl.delete_ticket;
    open c_actual for
        SELECT PROJECT_ID, TICKET_ID
        FROM OMS_TICKET_MST
        WHERE TICKET_ID = 109;
        
    open c_expected for
        SELECT 82 AS PROJECT_ID, 
           109 AS TICKET_ID
        FROM DUAL;
        
      -- assert
      ut.expect(c_actual).to_equal(c_expected);
   end delete_ticket;

   --
   -- test delete_project
   --
   procedure delete_project is
      l_actual   integer;
      l_expected integer;
   begin
      -- arrange

      -- act
      -- oms_project_manage_utl.delete_project;
    SELECT PROJECT_ID INTO l_actual FROM OMS_PROJECT_MST WHERE PROJECT_ID = 82;
    
      -- assert
      ut.expect(l_actual).to_equal(82);
   end delete_project;

end UT_OMS_PROJECT_MANAGE_UTL;

/
