--------------------------------------------------------
--  DDL for Package Body UT_OMS_WORKING_HRS_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_OMS_WORKING_HRS_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 16:56:13

   --
   -- test create_working_hrs
   --
procedure create_working_hrs is
    c_actual sys_refcursor;
    c_expected sys_refcursor;
begin
      -- arrange

      -- act
      -- oms_working_hrs_utl.create_working_hrs;
    open c_actual for
        SELECT EMP_TYPE_FK, 
            FROM_TIME, 
            TO_TIME, 
            COMP_ID, 
            FIN_ID
        FROM OMS_WORK_HRS_SLOTS
        WHERE TIME_ID = 176;
    
    open c_expected for
        SELECT 3 AS EMP_TYPE_FK, 
            '09:00AM' AS FROM_TIME, 
            '10:00AM' AS TO_TIME, 
            1 AS COMP_ID, 
            62 AS FIN_ID
        FROM DUAL;

      -- assert
    ut.expect(c_actual).to_equal(c_expected);
end create_working_hrs;

   --
   -- test allocate_working_hrs
   --
   procedure allocate_working_hrs is
      c_actual sys_refcursor;
      c_expected sys_refcursor;
   begin
      -- arrange

      -- act
      -- oms_working_hrs_utl.allocate_working_hrs;
    open c_actual for
        SELECT EMPLOYEE_ID, 
            EMPLOYEE_TYPE_ID, 
            COMP_ID, 
            FIN_ID
        FROM OMS_EMP_WORKING_HRS
        WHERE WORK_ID = 26160;
    
    open c_expected for
        SELECT 31 AS EMPLOYEE_ID, 
            41 AS EMPLOYEE_TYPE_ID, 
            1 AS COMP_ID, 
            62 AS FIN_ID
        FROM DUAL;
        
      -- assert
      ut.expect(c_actual).to_equal(c_expected);
   end allocate_working_hrs;

   --
   -- test create_working_hour_slots
   --
procedure create_working_hour_slots is
    c_actual sys_refcursor;
    c_expected sys_refcursor;
begin
      -- arrange

      -- act
      -- oms_working_hrs_utl.create_working_hour_slots;
    open c_actual for
        SELECT EMP_TYPE_FK, 
            FROM_TIME, 
            COMP_ID, 
            FIN_ID
        FROM OMS_WORK_HRS_SLOTS
        WHERE TIME_ID = 176;
    
    open c_expected for
        SELECT 3 AS EMP_TYPE_FK, 
            '09:00AM' AS FROM_TIME, 
            1 AS COMP_ID, 
            62 AS FIN_ID
        FROM DUAL;
        
      -- assert
    ut.expect(c_actual).to_equal(c_expected);
end create_working_hour_slots;

end UT_OMS_WORKING_HRS_UTL;

/
