--------------------------------------------------------
--  DDL for Package Body UT_OMS_LOGIN_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "INSTITUTE"."UT_OMS_LOGIN_PKG" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 15:06:21

   --
   -- test login
   --
procedure login is
    l_actual   boolean;
    l_expected boolean;
begin
      -- arrange

      -- act
      -- oms_login_package.login;
    l_actual := oms_login_package.login('ADMIN','ADMIN');
      -- assert
    ut.expect(l_actual).to_equal(true);
end login;

end UT_OMS_LOGIN_PKG;

/
