REM INSERTING into INSTITUTE.AEP_USER_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.AEP_USER_TYPE_MST (USER_TYPE_ID,USER_TYPE_CODE,USER_TYPE_NAME,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,STATUS) values (2,'ADM','Admin','SUPERADMIN@GMAIL.COM',to_timestamp('12-09-23 6:00:36.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,'Active');
Insert into INSTITUTE.AEP_USER_TYPE_MST (USER_TYPE_ID,USER_TYPE_CODE,USER_TYPE_NAME,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,STATUS) values (1,'SADM','Super Admin','nobody',to_timestamp('11-09-23 7:17:25.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),'SUPERADMIN@GMAIL.COM',to_timestamp('11-09-23 10:17:54.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),'Active');
