REM INSERTING into INSTITUTE.DEPARTMENT_MST
SET DEFINE OFF;
Insert into INSTITUTE.DEPARTMENT_MST (DEPT_ID,DEPT_NAME,INSTITUTE_ID) values (101,'Maths',36);
Insert into INSTITUTE.DEPARTMENT_MST (DEPT_ID,DEPT_NAME,INSTITUTE_ID) values (102,'Science',36);
Insert into INSTITUTE.DEPARTMENT_MST (DEPT_ID,DEPT_NAME,INSTITUTE_ID) values (103,'English',36);
