REM INSERTING into INSTITUTE.DEPT
SET DEFINE OFF;
Insert into INSTITUTE.DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCH','DALLAS');
Insert into INSTITUTE.DEPT (DEPTNO,DNAME,LOC) values (30,'SALES','CHICAGO');
Insert into INSTITUTE.DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONS','BOSTON');
