REM INSERTING into INSTITUTE.DISEASE_MST
SET DEFINE OFF;
Insert into INSTITUTE.DISEASE_MST (DISEASE_MAST_ID,DISEASE_NAME,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (27,'Bronchitis','GRIMA',to_timestamp('18-03-23 5:35:51.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
