REM INSERTING into INSTITUTE.EBA_DEMO_DG_DEPT
SET DEFINE OFF;
Insert into INSTITUTE.EBA_DEMO_DG_DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.EBA_DEMO_DG_DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EBA_DEMO_DG_DEPT (DEPTNO,DNAME,LOC) values (30,'SALES','CHICAGO');
Insert into INSTITUTE.EBA_DEMO_DG_DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONS','BOSTON');
