REM INSERTING into INSTITUTE.EMPLOYEE_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (121,'EMP01','Trainer',40);
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (101,'RIVTEAC','Teacher',38);
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (81,'DRAVIJDRI','Driver',36);
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (102,'RIVDRI','Driver',38);
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (61,'DRAVIJTEA','Teacher',36);
Insert into INSTITUTE.EMPLOYEE_TYPE_MST (TYPE_ID,TYPE_CODE,TYPE_NAME,INSTITUTE_ID) values (62,'DRAVIJCLK','Clerk',36);
