REM INSERTING into INSTITUTE.EMS_ERROR_LOOKUP
SET DEFINE OFF;
Insert into INSTITUTE.EMS_ERROR_LOOKUP (CONSTRAINT_NAME,MESSAGE,LANGUAGE_CODE) values ('EBA_PROJ_STATUS_PROJECT_UNQ','Project name already in use.','EN');
