REM INSERTING into INSTITUTE.EMS_CONTACT_US
SET DEFINE OFF;
Insert into INSTITUTE.EMS_CONTACT_US (CONTACT_ID,FULLNAME,CONTACT_NO,EMAIL_ID,COMPANY_NM,SUBJECT,QUESTION,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (1,'Demo',873283742,'demo@gmail.com',null,null,'question','nobody',to_timestamp('24-08-23 11:34:32.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
