REM INSERTING into INSTITUTE.EVENT_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (161,'Science Exhibition',36,'apex-cal-green');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (162,'Fancy Dress Competition',36,'apex-cal-gray');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (163,'Quiz Competition',36,'apex-cal-cyan');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (164,'Celebrating Festivals',36,'apex-cal-blue');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (201,'Workshop',40,'apex-cal-silver');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (165,'Weekly Test',36,'apex-cal-red');
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (181,'Seminar',38,null);
Insert into INSTITUTE.EVENT_TYPE_MST (EVENT_ID,EVENT_TYPE,INSTITUTE_ID,EVENT_COLOR) values (141,'Seminar',36,'apex-cal-yellow');
