REM INSERTING into INSTITUTE.FEES_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.FEES_TYPE_MST (FEES_TYPE_ID,FEES_TYPE_CODE,FEES_TYPE,DETAILS,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (44,'FEESSTD1','Annual Fees','Annual Fees',36,'ADMIN@DRAVIJ.COM',to_timestamp('11-02-23 10:04:23.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
