REM INSERTING into INSTITUTE.HOSTEL_MST
SET DEFINE OFF;
Insert into INSTITUTE.HOSTEL_MST (HOSTEL_ID,INSTITUTE_ID,HOSTEL_NAME,SHORTNAME,NOOFROOMS,HOSTEL_CODE,HOSTEL_TYPE,"DESC",STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (37,38,'Riverdale Girls Hostel','RBH','10','RIVHOSB','GIRLS',null,'Active','GRIMA',to_timestamp('18-03-23 5:35:51.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
Insert into INSTITUTE.HOSTEL_MST (HOSTEL_ID,INSTITUTE_ID,HOSTEL_NAME,SHORTNAME,NOOFROOMS,HOSTEL_CODE,HOSTEL_TYPE,"DESC",STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (36,36,'Dravij Boys Hostel',null,'10','DRAHOSB','BOYS',null,'Active','ADMIN@DRAVIJ.COM',to_timestamp('13-02-23 12:04:12.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
