REM INSERTING into INSTITUTE.LEAVE_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.LEAVE_TYPE_MST (LEAVE_TYPE_ID,LEAVE_CODE,LEAVE_NAME,DESCRIPTION,STATUS,MAX_LEAVE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,INSTITUTE_ID) values (6,'ML','Medical Leave',null,'Active',5,'ADMIN@DRAVIJ.COM',to_timestamp('09-02-23 12:39:58.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,36);
Insert into INSTITUTE.LEAVE_TYPE_MST (LEAVE_TYPE_ID,LEAVE_CODE,LEAVE_NAME,DESCRIPTION,STATUS,MAX_LEAVE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,INSTITUTE_ID) values (4,'BISMED','Medical Leave',null,'Active',5,null,null,null,null,33);
Insert into INSTITUTE.LEAVE_TYPE_MST (LEAVE_TYPE_ID,LEAVE_CODE,LEAVE_NAME,DESCRIPTION,STATUS,MAX_LEAVE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,INSTITUTE_ID) values (5,'BISSPORT','Sports Leave',null,'Active',2,null,null,null,null,33);
