REM INSERTING into INSTITUTE.LOGGER_PREFS
SET DEFINE OFF;
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('LOGGER_DEBUG','FALSE','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('PREF_BY_CLIENT_ID_EXPIRE_HOURS','12','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('PLUGIN_FN_ERROR','NONE','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('PURGE_MIN_LEVEL','DEBUG','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('INCLUDE_CALL_STACK','TRUE','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('INSTALL_SCHEMA','INSTITUTE','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('LEVEL','DEBUG','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('PURGE_AFTER_DAYS','7','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('PROTECT_ADMIN_PROCS','TRUE','LOGGER');
Insert into INSTITUTE.LOGGER_PREFS (PREF_NAME,PREF_VALUE,PREF_TYPE) values ('LOGGER_VERSION','3.1.1','LOGGER');
