REM INSERTING into INSTITUTE.MEDIUM_MST
SET DEFINE OFF;
Insert into INSTITUTE.MEDIUM_MST (MED_ID,MEDIUM_NAME,MED_SHORT_NAME,INSTITUTE_ID,AC_YEAR_ID,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (54,'English','ENG',36,36,'Active','ADMIN@DRAVIJ.COM',to_timestamp('06-02-23 9:51:21.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
Insert into INSTITUTE.MEDIUM_MST (MED_ID,MEDIUM_NAME,MED_SHORT_NAME,INSTITUTE_ID,AC_YEAR_ID,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (56,'English','ENGLISH',40,39,'Active','DIGVIJAY@OAC.COM',to_timestamp('17-04-23 1:04:58.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
Insert into INSTITUTE.MEDIUM_MST (MED_ID,MEDIUM_NAME,MED_SHORT_NAME,INSTITUTE_ID,AC_YEAR_ID,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (55,'English','ENG',38,38,'Active','GRIMA',to_timestamp('18-03-23 5:35:51.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null);
