REM INSERTING into INSTITUTE.POINTS_MST
SET DEFINE OFF;
Insert into INSTITUTE.POINTS_MST (POINT_ID,POINT_NAME,POINT_CODE,ROUTE_ID,INSTITUTE_ID,STATUS,"DESC",CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (7,'Point 1','TP1',6,36,'Active',null,null,null,null,null);
Insert into INSTITUTE.POINTS_MST (POINT_ID,POINT_NAME,POINT_CODE,ROUTE_ID,INSTITUTE_ID,STATUS,"DESC",CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (8,'Point 2','TP2',6,36,'Active',null,null,null,null,null);
Insert into INSTITUTE.POINTS_MST (POINT_ID,POINT_NAME,POINT_CODE,ROUTE_ID,INSTITUTE_ID,STATUS,"DESC",CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (9,'P1','P1',7,36,'Active',null,null,null,null,null);
Insert into INSTITUTE.POINTS_MST (POINT_ID,POINT_NAME,POINT_CODE,ROUTE_ID,INSTITUTE_ID,STATUS,"DESC",CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (10,'Point 1','STOP1',8,38,'Active',null,null,null,null,null);
