REM INSERTING into INSTITUTE.REST_FILE_UPLOAD
SET DEFINE OFF;
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (29,'Lighthouse.jpg','image/jpeg',to_timestamp('29-04-23 7:27:14.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (31,'Upload_Document.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',to_timestamp('29-04-23 7:29:49.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (36,'Webinar Registration backup.csv','application/vnd.ms-excel',to_timestamp('29-04-23 7:53:55.868554000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (50,'Desert.jpg','image/jpeg',to_timestamp('05-05-23 9:40:55.465828000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (34,'persona-female03.png','image/png',to_timestamp('29-04-23 7:38:36.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (35,'LJ Establish Date References.txt','text/plain',to_timestamp('29-04-23 7:45:29.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (37,'Theme Migration.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',to_timestamp('29-04-23 7:55:22.278452000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (38,'TempUsaMoversDirectory Discovery Report.txt','text/plain',to_timestamp('29-04-23 7:57:16.793726000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (47,'Upload Employee.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_timestamp('04-05-23 10:07:39.661865000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (48,'FEED.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_timestamp('04-05-23 10:10:00.433068000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (30,'Upload Subject.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_timestamp('29-04-23 7:29:15.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
Insert into INSTITUTE.REST_FILE_UPLOAD (FILE_ID,FILENAME,MIME_TYPE,CREATED_ON,FLEX2,FLEX3,CREATED_BY,UPDATED_BY,UPDATED_ON) values (32,'Upload_Interview_AnswersCSV.csv','text/csv',to_timestamp('29-04-23 7:30:04.000000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,null,null,null);
