REM INSERTING into INSTITUTE.ROUTE_MST
SET DEFINE OFF;
Insert into INSTITUTE.ROUTE_MST (ROUTE_ID,ROUTE_NAME,ROUTE_CODE,VEHICAL_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (7,'Bus Route 1','R1',8,36,null,null,null,null);
Insert into INSTITUTE.ROUTE_MST (ROUTE_ID,ROUTE_NAME,ROUTE_CODE,VEHICAL_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (8,'Bus Route 1','R1',10,38,null,null,null,null);
Insert into INSTITUTE.ROUTE_MST (ROUTE_ID,ROUTE_NAME,ROUTE_CODE,VEHICAL_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (6,'Route 1','R1',7,36,null,null,null,null);
