REM INSERTING into INSTITUTE.STUD_DOC_DET
SET DEFINE OFF;
Insert into INSTITUTE.STUD_DOC_DET (DOC_ID,STUDENT_ID,DOC_NAME,MIME_TYPE,LAST_UPDATED,DOC_DETAILS,SUBMITTED_DT,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,APPROVED_STATUS) values (50,409,'ABC','image/jpeg',to_date('22-08-23','DD-MM-RR'),'ABC',to_date('22-08-23','DD-MM-RR'),36,null,null,null,null,0);
Insert into INSTITUTE.STUD_DOC_DET (DOC_ID,STUDENT_ID,DOC_NAME,MIME_TYPE,LAST_UPDATED,DOC_DETAILS,SUBMITTED_DT,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,APPROVED_STATUS) values (45,411,'Certificate',null,null,'Certificate',to_date('17-02-23','DD-MM-RR'),36,null,null,null,null,1);
Insert into INSTITUTE.STUD_DOC_DET (DOC_ID,STUDENT_ID,DOC_NAME,MIME_TYPE,LAST_UPDATED,DOC_DETAILS,SUBMITTED_DT,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,APPROVED_STATUS) values (46,409,'Certificate',null,null,null,to_date('25-02-23','DD-MM-RR'),36,null,null,null,null,1);
