REM INSERTING into INSTITUTE.STUDENT_LEAVE_DETAILS
SET DEFINE OFF;
Insert into INSTITUTE.STUDENT_LEAVE_DETAILS (LEAVE_ID,LEAVE_TYPE_ID,STUDENT_ID,MED_ID,STD_ID,SEM_ID,DIV_ID,FROM_DATE,TO_DATE,INSTITUTE_ID,AC_YEAR_ID,NO_OF_DAYS,EMPLOYEE_ID) values (23,6,410,54,40,null,57,to_date('09-01-23','DD-MM-RR'),to_date('09-01-23','DD-MM-RR'),36,36,1,70);
Insert into INSTITUTE.STUDENT_LEAVE_DETAILS (LEAVE_ID,LEAVE_TYPE_ID,STUDENT_ID,MED_ID,STD_ID,SEM_ID,DIV_ID,FROM_DATE,TO_DATE,INSTITUTE_ID,AC_YEAR_ID,NO_OF_DAYS,EMPLOYEE_ID) values (4,6,409,54,40,null,57,to_date('03-02-23','DD-MM-RR'),to_date('03-02-23','DD-MM-RR'),36,36,1,70);
