REM INSERTING into INSTITUTE.TIME_MST
SET DEFINE OFF;
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (56,null,'2023','08:30','09:00',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (57,null,'2023','09:05','09:35',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (54,null,'2023','07:00','07:45',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (63,null,'2023','08:00','09:00',40,39,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (55,null,'2023','07:50','08:30',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (60,null,'2023','11:15','11:50',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (61,null,'2023','11:55','12:30',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (62,null,'2023','07:00','07:30',38,38,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (58,null,'2023','10:00','10:30',36,36,null,'A',null,null,null,null);
Insert into INSTITUTE.TIME_MST (TIME_ID,MONTH,YEAR,FROM_TIME,TO_TIME,INSTITUTE_ID,AC_YEAR_ID,DETAILS,STATUS,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (59,null,'2023','10:35','11:15',36,36,null,'A',null,null,null,null);
