REM INSERTING into INSTITUTE.TRANSPORT_DET
SET DEFINE OFF;
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (14,420,9,8,'TRANS2',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (16,442,10,10,'RIVTRA',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (10,421,8,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (7,409,8,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (8,410,7,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (9,411,7,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (11,422,7,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (12,423,7,7,'TCODE1',null,null,null,null);
Insert into INSTITUTE.TRANSPORT_DET (TRANSPORT_ID,STUDENT_ID,POINT_ID,VEHICAL_ID,TRANSPORT_CODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (13,424,7,7,'TCODE1',null,null,null,null);
