REM INSERTING into INSTITUTE.VEHICAL_MST
SET DEFINE OFF;
Insert into INSTITUTE.VEHICAL_MST (VEHICAL_ID,VEHICAL_TYPE,VEHICAL_NO,VEHICAL_CODE,VEHICAL_CAPACITY,DRIVER_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (8,'Bus','GJ QE 3442','VHBUS','25',1,36,null,null,null,null);
Insert into INSTITUTE.VEHICAL_MST (VEHICAL_ID,VEHICAL_TYPE,VEHICAL_NO,VEHICAL_CODE,VEHICAL_CAPACITY,DRIVER_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (7,'Van/Car','GJ AD 1220','VAN1220','7',1,36,null,null,null,null);
Insert into INSTITUTE.VEHICAL_MST (VEHICAL_ID,VEHICAL_TYPE,VEHICAL_NO,VEHICAL_CODE,VEHICAL_CAPACITY,DRIVER_ID,INSTITUTE_ID,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values (10,'Bus','GJ23QE1221','VHBUS','25',2,38,null,null,null,null);
