REM INSERTING into INSTITUTE.XXX_USER_TYPE_MST
SET DEFINE OFF;
Insert into INSTITUTE.XXX_USER_TYPE_MST (USER_TYPE_ID,USER_TYPE_CODE,USER_TYPE_NAME,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,STATUS) values (34,'ADM','Admin','nobody',to_timestamp('16-08-23 2:25:31.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null,null,'Active');
