REM INSERTING into INSTITUTE.EMP_DEPT_V
SET DEFINE OFF;
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7839,'KING','PRESIDENT',null,to_date('17-11-81','DD-MM-RR'),5000,null,10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7782,'CLARK','MANAGER','KING',to_date('09-06-81','DD-MM-RR'),2450,null,10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7934,'MILLER','CLERK','CLARK',to_date('23-01-82','DD-MM-RR'),1300,null,10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (8003,'JULIE','MANAGER',null,to_date('17-11-81','DD-MM-RR'),8000,null,10,'ACCOUNTING','NEW YORK');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7566,'JONES','MANAGER','KING',to_date('02-04-81','DD-MM-RR'),2975,null,20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7788,'SCOTT','ANALYST','JONES',to_date('09-12-82','DD-MM-RR'),3000,null,20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7902,'FORD','ANALYST','JONES',to_date('03-12-81','DD-MM-RR'),3000,null,20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7369,'SMITH','CLERK','FORD',to_date('17-12-80','DD-MM-RR'),800,null,20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7876,'ADAMS','CLERK','SCOTT',to_date('12-01-83','DD-MM-RR'),1100,null,20,'RESEARCH','DALLAS');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7698,'BLAKE','MANAGER','KING',to_date('01-05-81','DD-MM-RR'),2850,null,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7499,'ALLEN','SALESMAN','BLAKE',to_date('20-02-81','DD-MM-RR'),1600,300,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7521,'WARD','SALESMAN','BLAKE',to_date('22-02-81','DD-MM-RR'),1250,500,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7654,'MARTIN','SALESMAN','BLAKE',to_date('28-09-81','DD-MM-RR'),1250,1400,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7844,'TURNER','SALESMAN','BLAKE',to_date('08-09-81','DD-MM-RR'),1500,0,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (7900,'JAMES','CLERK','BLAKE',to_date('03-12-81','DD-MM-RR'),950,null,30,'SALES','CHICAGO');
Insert into INSTITUTE.EMP_DEPT_V (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC) values (8004,null,null,null,null,null,null,null,null,null);
