--------------------------------------------------------
--  Constraints for Table ACADEMIC_YEAR_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" MODIFY ("START_YEAR" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" MODIFY ("END_YEAR" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" ADD CONSTRAINT "AC_YEAR_MAST_PK" PRIMARY KEY ("AC_YEAR_ID")
  USING INDEX "INSTITUTE"."AC_YEAR_MAST_PK"  ENABLE;
