--------------------------------------------------------
--  Constraints for Table ADMISSION_APPLICATION
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("ADM_APPL_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("ADM_APPL_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("MIDDLENAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("MOBILE_NO" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ADMISSION_APPLICATION" ADD CONSTRAINT "ADMISSION_APPLICATION_PK" PRIMARY KEY ("ADM_APPL_ID")
  USING INDEX "INSTITUTE"."ADMISSION_APPLICATION_PK"  ENABLE;
