--------------------------------------------------------
--  Constraints for Table AEP_USER_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."AEP_USER_MST" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AEP_USER_MST" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AEP_USER_MST" ADD CONSTRAINT "AEP_USER_MST_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."AEP_USER_MST" ADD CONSTRAINT "AEP_USER_MST_UNQ_CON" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
