--------------------------------------------------------
--  Constraints for Table ASSIGN_SUB_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."ASSIGN_SUB_DET" MODIFY ("ASSIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."ASSIGN_SUB_DET" ADD CONSTRAINT "ASSIGN_SUB_DET_PK" PRIMARY KEY ("ASSIGN_ID")
  USING INDEX "INSTITUTE"."ASSIGN_SUB_DET_PK"  ENABLE;
  ALTER TABLE "INSTITUTE"."ASSIGN_SUB_DET" ADD CONSTRAINT "ASSIGN_SUB_DET_CON" UNIQUE ("STD_ID", "DIV_ID", "SUB_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
