--------------------------------------------------------
--  Constraints for Table AT_STUD_ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."AT_STUD_ATTENDANCE" MODIFY ("ATTEND_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AT_STUD_ATTENDANCE" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AT_STUD_ATTENDANCE" ADD CONSTRAINT "AT_STUD_ATTENDANCE_PK" PRIMARY KEY ("ATTEND_ID")
  USING INDEX "INSTITUTE"."AT_STUD_ATTENDANCE_PK"  ENABLE;
  ALTER TABLE "INSTITUTE"."AT_STUD_ATTENDANCE" MODIFY ("SCHEDULE_ID_FK" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AT_STUD_ATTENDANCE" MODIFY ("MED_ID" NOT NULL ENABLE);
