--------------------------------------------------------
--  Constraints for Table AUTO_SCHEDULER
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("AUTO_SCH_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("SCH_DATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("SCH_DAY" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("TIME_ID_FK" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("MED_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("STD_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("SUB_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("SUB_CREDIT" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."AUTO_SCHEDULER" ADD CONSTRAINT "AUTO_SCHEDULE_PK" PRIMARY KEY ("AUTO_SCH_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
