--------------------------------------------------------
--  Constraints for Table BOOKISSUE_QUOTA_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."BOOKISSUE_QUOTA_MST" MODIFY ("BOOKQTID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKISSUE_QUOTA_MST" MODIFY ("LIB_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKISSUE_QUOTA_MST" ADD CONSTRAINT "BOOKISSUE_QUOTA_MST_PK" PRIMARY KEY ("BOOKQTID")
  USING INDEX "INSTITUTE"."BOOKISSUE_QUOTA_MST_PK"  ENABLE;
