--------------------------------------------------------
--  Constraints for Table BOOKSLISTDET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."BOOKSLISTDET" MODIFY ("BOOKID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSLISTDET" MODIFY ("LIB_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSLISTDET" MODIFY ("BOOKCAT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSLISTDET" ADD CONSTRAINT "BOOKSLISTDET_PK" PRIMARY KEY ("BOOKID")
  USING INDEX "INSTITUTE"."BOOKSLISTDET_PK"  ENABLE;
