--------------------------------------------------------
--  Constraints for Table BOOKSISSUEDET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."BOOKSISSUEDET" MODIFY ("BOOKISSUEID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSISSUEDET" MODIFY ("BOOKID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSISSUEDET" ADD CONSTRAINT "BOOKSISSUEDET_PK" PRIMARY KEY ("BOOKISSUEID")
  USING INDEX "INSTITUTE"."BOOKSISSUEDET_PK"  ENABLE;
