--------------------------------------------------------
--  Constraints for Table BOOKSCATEGORYDET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."BOOKSCATEGORYDET" MODIFY ("BOOKCAT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSCATEGORYDET" MODIFY ("LIB_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."BOOKSCATEGORYDET" ADD CONSTRAINT "BOOKSCATEGORYDET_PK" PRIMARY KEY ("BOOKCAT_ID")
  USING INDEX "INSTITUTE"."BOOKSCATEGORYDET_PK"  ENABLE;
