--------------------------------------------------------
--  Constraints for Table DIVISION_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."DIVISION_MST" MODIFY ("DIVISION_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."DIVISION_MST" MODIFY ("DIV_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."DIVISION_MST" MODIFY ("STD_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."DIVISION_MST" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."DIVISION_MST" ADD CONSTRAINT "DIVISION_MAST_PK" PRIMARY KEY ("DIVISION_ID")
  USING INDEX "INSTITUTE"."DIVISION_MAST_PK"  ENABLE;
