--------------------------------------------------------
--  Constraints for Table EBA_DEMO_DG_ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" MODIFY ("LINE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" ADD CONSTRAINT "EBA_DEMO_DG_OI_PK" PRIMARY KEY ("ORDER_ID", "LINE_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" ADD CONSTRAINT "EBA_DEMO_DG_OI_PROD_U" UNIQUE ("PRODUCT_ID", "ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
