--------------------------------------------------------
--  Constraints for Table EBA_DEMO_DG_ORDERS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" MODIFY ("ORDER_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" ADD CONSTRAINT "EBA_DEMO_DG_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_ORDERS" ADD CONSTRAINT "EBA_DEMO_DG_ORD_STATUS_C" CHECK (order_status in ('CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED')) ENABLE;
