--------------------------------------------------------
--  Constraints for Table EBA_DEMO_DG_PRODUCTS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_PRODUCTS" ADD CONSTRAINT "EBA_DEMO_DG_PROD_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
