--------------------------------------------------------
--  Constraints for Table EBA_DEMO_DG_CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_CUSTOMERS" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_CUSTOMERS" MODIFY ("EMAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_CUSTOMERS" ADD CONSTRAINT "EBA_DEMO_DG_CUST_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."EBA_DEMO_DG_CUSTOMERS" ADD CONSTRAINT "EBA_DEMO_DG_CUST_EMAIL_U" UNIQUE ("EMAIL_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
