--------------------------------------------------------
--  Constraints for Table EMAIL_TEMPLATE
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EMAIL_TEMPLATE" MODIFY ("ET_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMAIL_TEMPLATE" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMAIL_TEMPLATE" ADD CONSTRAINT "EMAIL_TEMPLATE_PK" PRIMARY KEY ("ET_ID")
  USING INDEX "INSTITUTE"."EMAIL_TEMPLATE_PK"  ENABLE;
