--------------------------------------------------------
--  Constraints for Table EMP_PAYROLL_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EMP_PAYROLL_DET" MODIFY ("PAY_DET_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMP_PAYROLL_DET" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMP_PAYROLL_DET" ADD CONSTRAINT "EMP_PAYROLL_DET_PK" PRIMARY KEY ("PAY_DET_ID")
  USING INDEX "INSTITUTE"."EMP_PAYROLL_DET_PK"  ENABLE;
