--------------------------------------------------------
--  Constraints for Table EMPLOYEE_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EMPLOYEE_DET" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMPLOYEE_DET" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMPLOYEE_DET" ADD CONSTRAINT "EMPLOYEE_DET_CON" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX "INSTITUTE"."EMPLOYEE_DET_CON"  ENABLE;
