--------------------------------------------------------
--  Constraints for Table EMS_EMAIL
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("EMAIL_PK" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("SENDER" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("MATTER" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("EMAIL_DATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."EMS_EMAIL" MODIFY ("PERTICULARS" NOT NULL ENABLE);
