--------------------------------------------------------
--  Constraints for Table FEES_STRUCTURE_YEARLY
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" MODIFY ("STRUCTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" MODIFY ("FEES_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" ADD CONSTRAINT "FEES_STRU_YEARLY_PK" PRIMARY KEY ("STRUCTURE_ID")
  USING INDEX "INSTITUTE"."FEES_STRU_YEARLY_PK"  ENABLE;
