--------------------------------------------------------
--  Constraints for Table GUARDIAN_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."GUARDIAN_DET" MODIFY ("GUARDIAN_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."GUARDIAN_DET" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."GUARDIAN_DET" ADD CONSTRAINT "GUARDIAN_DETAILS_PK" PRIMARY KEY ("GUARDIAN_ID")
  USING INDEX "INSTITUTE"."GUARDIAN_DETAILS_PK"  ENABLE;
