--------------------------------------------------------
--  Constraints for Table HEALTH_REPORT
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" MODIFY ("DISEASE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" MODIFY ("DISEASE_MAST_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HEALTH_REPORT" ADD CONSTRAINT "HEALTH_REPORT_PK" PRIMARY KEY ("DISEASE_ID")
  USING INDEX "INSTITUTE"."HEALTH_REPORT_PK"  ENABLE;
