--------------------------------------------------------
--  Constraints for Table HOSTEL_FEES_STRUCTURE
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_STRUCTURE" MODIFY ("FEE_STRU_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_STRUCTURE" MODIFY ("HOSTEL_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_STRUCTURE" ADD CONSTRAINT "HOSTEL_FEES_STRUCTURE_PK" PRIMARY KEY ("FEE_STRU_ID")
  USING INDEX "INSTITUTE"."HOSTEL_FEES_STRUCTURE_PK"  ENABLE;
