--------------------------------------------------------
--  Constraints for Table HOSTEL_FEES_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_DET" MODIFY ("HSTL_FEES_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_DET" MODIFY ("HOSTEL_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_FEES_DET" ADD CONSTRAINT "HOSTEL_FEES_DET_PK" PRIMARY KEY ("HSTL_FEES_ID")
  USING INDEX "INSTITUTE"."HOSTEL_FEES_DET_PK"  ENABLE;
