--------------------------------------------------------
--  Constraints for Table HOSTEL_ROOM_ASSIGN_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."HOSTEL_ROOM_ASSIGN_DET" MODIFY ("ROOM_ASSIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_ROOM_ASSIGN_DET" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."HOSTEL_ROOM_ASSIGN_DET" ADD CONSTRAINT "HOSTEL_ROOM_ASSIGN_DET_PK" PRIMARY KEY ("ROOM_ASSIGN_ID")
  USING INDEX "INSTITUTE"."HOSTEL_ROOM_ASSIGN_DET_PK"  ENABLE;
