--------------------------------------------------------
--  Constraints for Table INSTITUTE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INST_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INSTITUTE_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INST_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INST_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INST_STATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" MODIFY ("INST_CITY" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_MST" ADD CONSTRAINT "INSTITUTE_MAST_PK" PRIMARY KEY ("INSTITUTE_ID")
  USING INDEX "INSTITUTE"."INSTITUTE_MAST_PK"  ENABLE;
