--------------------------------------------------------
--  Constraints for Table INSTITUTE_CALENDAR
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."INSTITUTE_CALENDAR" MODIFY ("CAL_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_CALENDAR" MODIFY ("CAL_DATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_CALENDAR" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_CALENDAR" MODIFY ("EVENT_DETAILS" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."INSTITUTE_CALENDAR" ADD CONSTRAINT "INSTITUTE_CALENDAR_PK" PRIMARY KEY ("CAL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
