--------------------------------------------------------
--  Constraints for Table LEAVE_TYPE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LEAVE_TYPE_MST" ADD CONSTRAINT "LEAVE_TYPE_MST_CON" PRIMARY KEY ("LEAVE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
