--------------------------------------------------------
--  Constraints for Table LIBFINEDET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LIBFINEDET" MODIFY ("LIBFINID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LIBFINEDET" MODIFY ("BOOKISSUEID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LIBFINEDET" ADD CONSTRAINT "LIBFINEDET_PK" PRIMARY KEY ("LIBFINID")
  USING INDEX "INSTITUTE"."LIBFINEDET_PK"  ENABLE;
