--------------------------------------------------------
--  Constraints for Table LOGGER_LOGS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LOGGER_LOGS" ADD CONSTRAINT "LOGGER_LOGS_LVL_CK" CHECK (logger_level in (1,2,4,8,16,32,64,128)) ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS" ADD CONSTRAINT "LOGGER_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS" MODIFY ("LOGGER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
