--------------------------------------------------------
--  Constraints for Table LOGGER_PREFS_BY_CLIENT_ID
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" MODIFY ("LOGGER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" MODIFY ("INCLUDE_CALL_STACK" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" ADD CONSTRAINT "LOGGER_PREFS_BY_CLIENT_ID_CK2" CHECK (expiry_date >= created_date) ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" ADD CONSTRAINT "LOGGER_PREFS_BY_CLIENT_ID_CK3" CHECK (include_call_stack in ('TRUE', 'FALSE')) ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" ADD CONSTRAINT "LOGGER_PREFS_BY_CLIENT_ID_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS_BY_CLIENT_ID" ADD CONSTRAINT "LOGGER_PREFS_BY_CLIENT_ID_CK1" CHECK (logger_level in ('OFF','PERMANENT','ERROR','WARNING','INFORMATION','DEBUG','TIMING', 'APEX', 'SYS_CONTEXT')) ENABLE;
