--------------------------------------------------------
--  Constraints for Table LOGGER_PREFS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LOGGER_PREFS" MODIFY ("PREF_VALUE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS" ADD CONSTRAINT "LOGGER_PREFS_PK" PRIMARY KEY ("PREF_TYPE", "PREF_NAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS" MODIFY ("PREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS" ADD CONSTRAINT "LOGGER_PREFS_CK1" CHECK (pref_name = upper(pref_name)) ENABLE;
  ALTER TABLE "INSTITUTE"."LOGGER_PREFS" ADD CONSTRAINT "LOGGER_PREFS_CK2" CHECK (pref_type = upper(pref_type)) ENABLE;
