--------------------------------------------------------
--  Constraints for Table LOGGER_LOGS_APEX_ITEMS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" MODIFY ("APP_SESSION" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" ADD CONSTRAINT "LOGGER_LOGS_APX_ITMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
