--------------------------------------------------------
--  Constraints for Table MESSAGE_GROUPS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."MESSAGE_GROUPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."MESSAGE_GROUPS" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."MESSAGE_GROUPS" ADD CONSTRAINT "MESSAGE_GROUPS_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX "INSTITUTE"."MESSAGE_GROUPS_PK"  ENABLE;
