--------------------------------------------------------
--  Constraints for Table MOVERGEOG_JSON
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD CONSTRAINT "EMP_DATA_JSON" CHECK ("MOVER_ID" IS JSON  FORMAT JSON (LAX)) ENABLE;
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD CONSTRAINT "VERIFIED_LOC_JSON" CHECK ( VERIFIED_LOC is json ) ENABLE;
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD CONSTRAINT "VERIFIED_INTE_JSON" CHECK ( VERIFIED_INTE is json ) ENABLE;
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD CONSTRAINT "ELITE_LOC_JSON" CHECK ( ELITE_LOC is json ) ENABLE;
  ALTER TABLE "INSTITUTE"."MOVERGEOG_JSON" ADD CONSTRAINT "ELITE_INTE_JSON" CHECK ( ELITE_INTE is json ) ENABLE;
