--------------------------------------------------------
--  Constraints for Table SEMESTER_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."SEMESTER_MST" MODIFY ("SEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SEMESTER_MST" MODIFY ("SEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SEMESTER_MST" MODIFY ("STD_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SEMESTER_MST" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SEMESTER_MST" ADD CONSTRAINT "SEMESTER_MAST_PK" PRIMARY KEY ("SEM_ID")
  USING INDEX "INSTITUTE"."SEMESTER_MAST_PK"  ENABLE;
