--------------------------------------------------------
--  Constraints for Table SPECDEMO
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."SPECDEMO" MODIFY ("ID_1" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SPECDEMO" ADD PRIMARY KEY ("ID_1")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
