--------------------------------------------------------
--  Constraints for Table STANDARD_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("STD_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("STD_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("STD_SHORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("MED_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STANDARD_MST" ADD CONSTRAINT "STANDARD_MAST_PK" PRIMARY KEY ("STD_ID")
  USING INDEX "INSTITUTE"."STANDARD_MAST_PK"  ENABLE;
