--------------------------------------------------------
--  Constraints for Table STATE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STATE_MST" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STATE_MST" MODIFY ("COUNTRIES_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STATE_MST" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STATE_MST" MODIFY ("STATE_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STATE_MST" ADD CONSTRAINT "STATE_MAST_PK" PRIMARY KEY ("STATE_ID")
  USING INDEX "INSTITUTE"."STATE_MAST_PK"  ENABLE;
