--------------------------------------------------------
--  Constraints for Table STUD_PAR_MAP
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STUD_PAR_MAP" MODIFY ("MAP_ID_PK" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUD_PAR_MAP" ADD CONSTRAINT "STUD_PAR_MAP_PK" PRIMARY KEY ("MAP_ID_PK")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
