--------------------------------------------------------
--  Constraints for Table STUDENTS_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STUDENTS_DET" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUDENTS_DET" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUDENTS_DET" ADD CONSTRAINT "STUDENTS_DETAILS_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX "INSTITUTE"."STUDENTS_DETAILS_PK"  ENABLE;
