--------------------------------------------------------
--  Constraints for Table STUDENT_LEAVE_DETAILS
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."STUDENT_LEAVE_DETAILS" MODIFY ("LEAVE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUDENT_LEAVE_DETAILS" MODIFY ("LEAVE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUDENT_LEAVE_DETAILS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."STUDENT_LEAVE_DETAILS" ADD CONSTRAINT "STUDENT_LEAVE_DETAILS_PK" PRIMARY KEY ("LEAVE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
