--------------------------------------------------------
--  Constraints for Table SUBJECT_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."SUBJECT_MST" MODIFY ("SUB_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SUBJECT_MST" MODIFY ("SUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SUBJECT_MST" MODIFY ("SUBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SUBJECT_MST" MODIFY ("AC_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."SUBJECT_MST" ADD CONSTRAINT "SUBJECT_MASTER_PK" PRIMARY KEY ("SUB_ID")
  USING INDEX "INSTITUTE"."SUBJECT_MASTER_PK"  ENABLE;
