--------------------------------------------------------
--  Constraints for Table TIMETABLE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."TIMETABLE_MST" MODIFY ("TIMEMST_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE_MST" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE_MST" ADD CONSTRAINT "TIMETABLE_MST_PK" PRIMARY KEY ("TIMEMST_ID")
  USING INDEX "INSTITUTE"."TIMETABLE_MST_PK"  ENABLE;
