--------------------------------------------------------
--  Constraints for Table TIMETABLE
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."TIMETABLE" MODIFY ("TIMETBL_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE" MODIFY ("TIME_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE" MODIFY ("ASSIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE" MODIFY ("INSTITUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_PK" PRIMARY KEY ("TIMETBL_ID")
  USING INDEX "INSTITUTE"."TIMETABLE_PK"  ENABLE;
