--------------------------------------------------------
--  Constraints for Table TRANSPORT_DET
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" MODIFY ("TRANSPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" MODIFY ("POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."TRANSPORT_DET" ADD CONSTRAINT "TRANSPORT_DETAILS_PK" PRIMARY KEY ("TRANSPORT_ID")
  USING INDEX "INSTITUTE"."TRANSPORT_DETAILS_PK"  ENABLE;
