--------------------------------------------------------
--  Constraints for Table USERS_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."USERS_MST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_MST" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_MST" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_MST" MODIFY ("USER_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_MST" ADD CONSTRAINT "USERS_MAST_PK" PRIMARY KEY ("USER_ID")
  USING INDEX "INSTITUTE"."USERS_MAST_PK"  ENABLE;
