--------------------------------------------------------
--  Constraints for Table USERS_TYPE_MST
--------------------------------------------------------

  ALTER TABLE "INSTITUTE"."USERS_TYPE_MST" MODIFY ("USER_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_TYPE_MST" MODIFY ("USER_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_TYPE_MST" MODIFY ("USER_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "INSTITUTE"."USERS_TYPE_MST" ADD CONSTRAINT "USERS_TYPE_MST_PK" PRIMARY KEY ("USER_TYPE_ID")
  USING INDEX "INSTITUTE"."USERS_TYPE_MST_PK"  ENABLE;
