--------------------------------------------------------
--  DDL for Table ACADEMIC_YEAR_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."ACADEMIC_YEAR_MST" 
   (	"AC_YEAR_ID" NUMBER, 
	"YEAR_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"START_YEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"END_YEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"INSTITUTE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
