--------------------------------------------------------
--  DDL for Table AEP_USER_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."AEP_USER_MST" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRSTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_TYPE_ID" NUMBER, 
	"MOBILE_NO" NUMBER, 
	"RECOVERY_EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_LOGIN" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
