--------------------------------------------------------
--  DDL for Table AUTO_SCHEDULER
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."AUTO_SCHEDULER" 
   (	"AUTO_SCH_ID" NUMBER, 
	"SCH_DATE" DATE, 
	"SCH_DAY" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"TIME_ID_FK" NUMBER, 
	"MED_ID" NUMBER, 
	"STD_ID" NUMBER, 
	"SEM_ID" NUMBER, 
	"DIV_ID" NUMBER, 
	"SUB_ID" NUMBER, 
	"SUB_CREDIT" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER(5,0), 
	"AC_YEAR_ID" NUMBER(5,0), 
	"FLEX_COL1" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX_COL2" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX_COL3" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX_COL4" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
