--------------------------------------------------------
--  DDL for Table BOOKSLISTDET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."BOOKSLISTDET" 
   (	"BOOKID" NUMBER, 
	"LIB_ID" NUMBER, 
	"BOOKCAT_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"BOOKNAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOKCODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTHORNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PUBLICATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOOFCOPY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BARCODEDET" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOKIMAGE" BLOB, 
	"MIMETYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARSET" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"BOOK_EDITION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AVAIL_BOOKS" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("BOOKIMAGE") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
