--------------------------------------------------------
--  DDL for Table DRIVER_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."DRIVER_MST" 
   (	"DRIVER_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOB" DATE, 
	"AGE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MARITIAL_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"ZIPCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAILID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILENO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
