--------------------------------------------------------
--  DDL for Table EBA_DEMO_DG_ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EBA_DEMO_DG_ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER, 
	"LINE_ITEM_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"UNIT_PRICE" NUMBER(10,2), 
	"QUANTITY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
