--------------------------------------------------------
--  DDL for Table EMAILS_ARC
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMAILS_ARC" 
   (	"E_ID" NUMBER, 
	"USER_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TO" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FROM" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BODY" CLOB COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EDATE" DATE, 
	"ETIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"CC" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
