--------------------------------------------------------
--  DDL for Table EMAIL_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMAIL_ATTACHMENTS" 
   (	"EMAIL_ATACH_ID" NUMBER, 
	"E_ID" NUMBER, 
	"TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DOCBLOB" BLOB, 
	"CHARSET" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MIMETYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATED" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("DOCBLOB") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
