--------------------------------------------------------
--  DDL for Table EMAIL_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMAIL_TEMPLATE" 
   (	"ET_ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPLATE_BODY" CLOB COLLATE "USING_NLS_COMP", 
	"USER_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"CREATE_DATE" DATE, 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("TEMPLATE_BODY") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
