--------------------------------------------------------
--  DDL for Table EMP_PAYROLL_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMP_PAYROLL_DET" 
   (	"PAY_DET_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"BASIC" NUMBER(12,2), 
	"HRA" NUMBER(12,2), 
	"SP_ALLOWANCE" NUMBER(12,2), 
	"MEDICAL" NUMBER(12,2), 
	"LTA" NUMBER(12,2), 
	"PF" NUMBER(12,2), 
	"ESI" NUMBER(12,2), 
	"TOTALSAL" NUMBER(12,2), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"GRADEPAY" NUMBER(10,0), 
	"IT" NUMBER(10,0), 
	"PT" NUMBER(10,0), 
	"DA" NUMBER(20,0), 
	"INSTITUTE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
