--------------------------------------------------------
--  DDL for Table EMP_EDUCATION_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMP_EDUCATION_DET" 
   (	"EDU_DET_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"DEGREE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSING_YR" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSING_MNT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EXAM_BOARD" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SCHOOL_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PERCENTAGE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SPECIAL_ACHI" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DESC" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
