--------------------------------------------------------
--  DDL for Table EMP_DOCUMENTS_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMP_DOCUMENTS_DET" 
   (	"DOC_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"DOC_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DOC_DESC" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BLOB_CONTENT" BLOB, 
	"MIME_TYPE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CHAR_SET" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("BLOB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
