--------------------------------------------------------
--  DDL for Table EMPLOYEE_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMPLOYEE_DET" 
   (	"EMPLOYEE_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"EMPLOYEE_TYPE_ID" NUMBER, 
	"EMPLOYEE_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRSTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOB" DATE, 
	"AGE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MARITIAL_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"ZIPCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_ADD" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_STATE_ID" NUMBER, 
	"TEMP_COUNTRY_ID" NUMBER, 
	"TEMP_ZIP" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAILID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTNO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILENO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHER_CONT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BLOODGROUP" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"HEALT_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_PROFILE_TITLE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"JOINNING DATE" DATE, 
	"JOB_TITLE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT" NUMBER, 
	"POSITION" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "INSTITUTE"."EMPLOYEE_DET" TO "ORDS_PLSQL_GATEWAY";
  GRANT INSERT ON "INSTITUTE"."EMPLOYEE_DET" TO "ORDS_PLSQL_GATEWAY";
  GRANT SELECT ON "INSTITUTE"."EMPLOYEE_DET" TO "ORDS_PLSQL_GATEWAY";
  GRANT UPDATE ON "INSTITUTE"."EMPLOYEE_DET" TO "ORDS_PLSQL_GATEWAY";
