--------------------------------------------------------
--  DDL for Table EMS_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMS_ERROR_LOG" 
   (	"ID" NUMBER, 
	"ERR_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"APP_ID" NUMBER, 
	"APP_PAGE_ID" NUMBER, 
	"APP_USER" VARCHAR2(512 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_AGENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IP_ADDRESS" VARCHAR2(512 BYTE) COLLATE "USING_NLS_COMP", 
	"IP_ADDRESS2" VARCHAR2(512 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_ITEM_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"REGION_ID" NUMBER, 
	"COLUMN_ALIAS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ROW_NUM" NUMBER, 
	"APEX_ERROR_CODE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ORA_SQLCODE" NUMBER, 
	"ORA_SQLERRM" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_BACKTRACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
