--------------------------------------------------------
--  DDL for Table EMS_DEMO_REQUEST_TBL
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMS_DEMO_REQUEST_TBL" 
   (	"REQUEST_ID" NUMBER, 
	"FULLNAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_NO" NUMBER, 
	"EMAIL_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_NM" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"DESIGNATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY_ID" NUMBER, 
	"STATE_ID" NUMBER, 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"REG_REFERENCE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
