--------------------------------------------------------
--  DDL for Table EMS_EMAIL
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMS_EMAIL" 
   (	"EMAIL_PK" NUMBER(7,0) DEFAULT 0, 
	"SENDER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RECEIVER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MATTER" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_DATE" DATE, 
	"USER_TYPE_ID" NUMBER(5,0) DEFAULT 0, 
	"LAST_LOGIN_FK" NUMBER(7,0), 
	"LAST_LOGIN_MODIFIED" TIMESTAMP (6), 
	"LAST_MC" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_IP" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PERTICULARS" NUMBER(1,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "INSTITUTE"."EMS_EMAIL" TO "TMS";
  GRANT INSERT ON "INSTITUTE"."EMS_EMAIL" TO "TMS";
  GRANT UPDATE ON "INSTITUTE"."EMS_EMAIL" TO "TMS";
