--------------------------------------------------------
--  DDL for Table EMS_MODULE_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."EMS_MODULE_MST" 
   (	"MODULE_ID" NUMBER, 
	"MODULE_NM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODULE_TYPE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"APP_ID" NUMBER, 
	"MODULE_PG" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTH_SCHEME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX2" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX3" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEX4" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"PARENT_ENTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEQ_ORDER" NUMBER, 
	"MODULE_ICON" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODULE_LEVEL" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
