--------------------------------------------------------
--  DDL for Table FEES_STRUCTURE_YEARLY
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."FEES_STRUCTURE_YEARLY" 
   (	"STRUCTURE_ID" NUMBER, 
	"FEES_TYPE_ID" NUMBER, 
	"MED_ID" NUMBER, 
	"STD_ID" NUMBER, 
	"SEM_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"AMOUNT" NUMBER(10,2), 
	"DUE_DATE" DATE, 
	"DISCOUNT_PER" NUMBER(10,2), 
	"CHARGE_AFTER_DUE_DT" NUMBER(10,2), 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"ALLOW_HALF_PAY" CHAR(5 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
