--------------------------------------------------------
--  DDL for Table HOSTEL_FEES_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."HOSTEL_FEES_DET" 
   (	"HSTL_FEES_ID" NUMBER, 
	"HOSTEL_ID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"FEE_STRU_ID" NUMBER, 
	"FEESDATE" DATE, 
	"STUDENT_ID" NUMBER, 
	"AC_YEARID" NUMBER, 
	"TERM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AMOUNT" NUMBER(12,2), 
	"FINAMOUNT" NUMBER(12,2), 
	"DIS_PER" NUMBER(12,2), 
	"DISCOUNTAMT" NUMBER(12,2), 
	"TOTAL_AMT" NUMBER(12,2), 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DESC" NUMBER(10,0), 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
