--------------------------------------------------------
--  DDL for Table INSTITUTE_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."INSTITUTE_MST" 
   (	"INSTITUTE_ID" NUMBER, 
	"INST_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"INST_ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"INST_COUNTRY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INST_STATE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INST_CITY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INST_LOGO" BLOB, 
	"LOGO_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CHAR_SET" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"WEB_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"REG_NO" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"TEL_PHONE_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"EMAIL_FLAG" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("INST_LOGO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
