--------------------------------------------------------
--  DDL for Table INSTITUTE_CALENDAR
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."INSTITUTE_CALENDAR" 
   (	"CAL_ID" NUMBER, 
	"CAL_DATE" DATE, 
	"EVENT_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_DETAILS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER(5,0), 
	"FLEX_COL3" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
