--------------------------------------------------------
--  DDL for Table LIBFINEDET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."LIBFINEDET" 
   (	"LIBFINID" NUMBER, 
	"FINDATE" DATE, 
	"STUDENTID" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"BOOKID" NUMBER, 
	"BOOKISSUEID" NUMBER, 
	"CHARGE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"AC_YEARID" NUMBER, 
	"LIB_ID" NUMBER, 
	"DESCR" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"EMPLOYEE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
