--------------------------------------------------------
--  DDL for Table LOGGER_LOGS_APEX_ITEMS
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."LOGGER_LOGS_APEX_ITEMS" 
   (	"ID" NUMBER, 
	"LOG_ID" NUMBER, 
	"APP_SESSION" NUMBER, 
	"ITEM_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_VALUE" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("ITEM_VALUE") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
