--------------------------------------------------------
--  DDL for Table LOGGER_LOGS
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."LOGGER_LOGS" 
   (	"ID" NUMBER, 
	"LOGGER_LEVEL" NUMBER, 
	"TEXT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TIME_STAMP" TIMESTAMP (6), 
	"SCOPE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"MODULE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CLIENT_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CALL_STACK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LINE_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SCN" NUMBER, 
	"EXTRA" CLOB COLLATE "USING_NLS_COMP", 
	"SID" NUMBER, 
	"CLIENT_INFO" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("EXTRA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
