--------------------------------------------------------
--  DDL for Table MEDIUM_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."MEDIUM_MST" 
   (	"MED_ID" NUMBER, 
	"MEDIUM_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MED_SHORT_NAME" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "INSTITUTE"."MEDIUM_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT INSERT ON "INSTITUTE"."MEDIUM_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT SELECT ON "INSTITUTE"."MEDIUM_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT UPDATE ON "INSTITUTE"."MEDIUM_MST" TO "ORDS_PLSQL_GATEWAY";
