--------------------------------------------------------
--  DDL for Table MESSAGE_GROUPS
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."MESSAGE_GROUPS" 
   (	"GROUP_ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_IDS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"GROUP_DESC" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"GROUP_ADMIN" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"GROUP_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
