--------------------------------------------------------
--  DDL for Table PARENTS_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."PARENTS_DET" 
   (	"PARENTS_ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" NUMBER, 
	"COUNTRY" NUMBER, 
	"PINCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILENO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONENO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OCCUPATION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICE_ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICEPHONE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICEMOBILE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTENSIONNO" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"USER_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER(5,0), 
	"ACADEMIC_STATUS" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
