--------------------------------------------------------
--  DDL for Table SAMPLE_ADMISSION_APPLICATION
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."SAMPLE_ADMISSION_APPLICATION" 
   (	"ADM_APPL_ID" NUMBER, 
	"ADM_APPL_CODE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRSTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_OF_BIRTH" DATE, 
	"AGE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"MOTHER_TONGUE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"RELIGION" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"FATHERNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"HOME_ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PINCODE" NUMBER(10,0), 
	"CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"TEL_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILE_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICE_ADDRESS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICE_PHONE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTENSION_NO" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICE_MOBILE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OCCUPATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MED_ID" NUMBER, 
	"STD_ID" NUMBER, 
	"PHOTO_TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTO" BLOB, 
	"PMIMETYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PCHARSET" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PLASTUPDATE" TIMESTAMP (6), 
	"STSIGN_TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STUDENT_SIGN" BLOB, 
	"SMIMETYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SCHARSET" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SPLASTUPDATE" TIMESTAMP (6), 
	"PRSIGN_TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_SIGN" BLOB, 
	"PSMIMETYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PSCHARSET" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PSLASTUPDATE" TIMESTAMP (6), 
	"INSTITUTE_ID" NUMBER, 
	"ADMISSION_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("PHOTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STUDENT_SIGN") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PARENT_SIGN") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
