--------------------------------------------------------
--  DDL for Table STATE_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."STATE_MST" 
   (	"STATE_ID" NUMBER, 
	"COUNTRIES_ID" NUMBER, 
	"STATE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_CODE" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
