--------------------------------------------------------
--  DDL for Table STUD_DOC_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."STUD_DOC_DET" 
   (	"DOC_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"DOC_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FILEBLOB" BLOB, 
	"MIME_TYPE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED" DATE, 
	"DOC_DETAILS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBMITTED_DT" DATE, 
	"INSTITUTE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"APPROVED_STATUS" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("FILEBLOB") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
