--------------------------------------------------------
--  DDL for Table STUDENTS_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."STUDENTS_DET" 
   (	"STUDENT_ID" NUMBER, 
	"ADM_APPL_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMISSION_DT" DATE, 
	"ADMISSION_YEAR" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ADM_MED" NUMBER, 
	"ADM_STD" NUMBER, 
	"ADM_SEM" NUMBER, 
	"INSTITUTE_ID" NUMBER, 
	"CUR_MED" NUMBER, 
	"CUR_STD" NUMBER, 
	"CUR_SEM" NUMBER, 
	"GR_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLL_NO" NUMBER(10,0), 
	"STUD_PHOTO" BLOB, 
	"FIRSTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOB" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"STUD_CONT_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STUD_MOBILE_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STUD_EMAIL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PERMNT_ADDR" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PERMNT_CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PERMNT_STATE" NUMBER, 
	"PERMNT_COUNTRY" NUMBER, 
	"PERMNT_PINCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_ADDR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_CITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMP_STATE" NUMBER, 
	"TEMP_COUNTRY" NUMBER, 
	"TEMP_PINCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FATHERNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FMIDDLENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FLASTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FCONT_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FMOBILE_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FATHER_OCCUPATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MOTHERNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MMIDDLENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MLASTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MCONT_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MMOBILE_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MOTHER_OCCUPATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_GRADUATE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"DIVISION_ID" NUMBER, 
	"ADM_APPL_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER(5,0), 
	"ACADEMIC_STATUS" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("STUD_PHOTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "INSTITUTE"."STUDENTS_DET" TO "TMS";
