--------------------------------------------------------
--  DDL for Table STUDENT_FEES_DET
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."STUDENT_FEES_DET" 
   (	"FEES_ID" NUMBER, 
	"RECEIPT_NO" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"FEES_DATE" TIMESTAMP (6), 
	"INSTITUTE_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"STD_ID" NUMBER, 
	"SEM_ID" NUMBER, 
	"FEES_TYPE_ID" NUMBER, 
	"AMOUNT" NUMBER(10,2), 
	"DISCOUNT_PER" NUMBER(10,2), 
	"DISCOUT_AMT" NUMBER(10,2), 
	"CHARGE_AFTER_DUE_DT" NUMBER(10,2), 
	"PAYMENT_TYPE" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_AMT" NUMBER(10,2), 
	"ALLOW_HALF_FEES" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DUE_AMOUNT" NUMBER(10,2), 
	"BANK_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUMMARY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CHEQUE_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CHEQUE_DT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
