--------------------------------------------------------
--  DDL for Table STUD_PAR_MAP
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."STUD_PAR_MAP" 
   (	"MAP_ID_PK" NUMBER(5,0), 
	"STUDENT_ID_FK" NUMBER(5,0), 
	"PARENTS_ID_FK" NUMBER(5,0), 
	"INSTITUTE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
