--------------------------------------------------------
--  DDL for Table SUBJECT_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."SUBJECT_MST" 
   (	"SUB_ID" NUMBER, 
	"SUB_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_TYPE" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"SEM_ID" NUMBER, 
	"STD_ID" NUMBER, 
	"AC_YEAR_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTITUTE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6), 
	"MED_ID" NUMBER(5,0), 
	"SUB_CREDIT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "INSTITUTE"."SUBJECT_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT INSERT ON "INSTITUTE"."SUBJECT_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT SELECT ON "INSTITUTE"."SUBJECT_MST" TO "ORDS_PLSQL_GATEWAY";
  GRANT UPDATE ON "INSTITUTE"."SUBJECT_MST" TO "ORDS_PLSQL_GATEWAY";
