--------------------------------------------------------
--  DDL for Table TMPPIVOTCLASS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "INSTITUTE"."TMPPIVOTCLASS" 
   (	"STUDENT_ID" NUMBER, 
	"SUBJECT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLLNO" NUMBER, 
	"LAC_NO" NUMBER, 
	"TIME" VARCHAR2(111 BYTE) COLLATE "USING_NLS_COMP", 
	"PRESENTS" NUMBER, 
	"OUTOF" NUMBER, 
	"PERCENTAGE" VARCHAR2(41 BYTE) COLLATE "USING_NLS_COMP", 
	"02/16/2022" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"02/17/2022" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"02/18/2022" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT PRESERVE ROWS ;
