--------------------------------------------------------
--  DDL for Table USERS_MST
--------------------------------------------------------

  CREATE TABLE "INSTITUTE"."USERS_MST" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRSTNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLENAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_TYPE_ID" NUMBER, 
	"LAST_LOGIN" TIMESTAMP (6), 
	"LOGIN_STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILENO" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"RECOVERY_EMAIL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTUTUTE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "INSTITUTE"."USERS_MST" TO "TMS";
  GRANT INSERT ON "INSTITUTE"."USERS_MST" TO "TMS";
  GRANT SELECT ON "INSTITUTE"."USERS_MST" TO "TMS";
  GRANT UPDATE ON "INSTITUTE"."USERS_MST" TO "TMS";
