--------------------------------------------------------
--  DDL for Package UT_APP_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_APP_UTIL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 13:08:55

   --%suite(ut_APP_UTIL)
   --%suitepath(alltests)

   --%test(returns user type id from user role)
   procedure get_usertypeid_fromrole;

   --%test
   procedure get_rolenamefrom_id;

   --%test
   procedure get_usernamefrom_id;

   --%test
   procedure get_useridfrom_username;

   --%test
   procedure get_instituteid_byusername;

   --%test
   procedure get_institutename_byid;

   --%test
   procedure get_inst_name_with_code;

   --%test
   procedure get_studentfullname_byid;

   --%test
   procedure get_calculate_age;

   --%test
   procedure get_employeename_byid;

   --%test
   procedure get_empid_byusername;

   --%test
   procedure get_userid_fromname;

end ut_APP_UTIL;

/
