--------------------------------------------------------
--  DDL for Package UT_EMS_PROMOTION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_EMS_PROMOTION" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 13:11:33

   --%suite(ut_EMS_PROMOTION)
   --%suitepath(alltests)

   --%test
   procedure class_settings;

   --%test
   procedure subject_settings;

end ut_EMS_PROMOTION;

/
