--------------------------------------------------------
--  DDL for Package UT_EMS_TEST_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_EMS_TEST_UTIL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 13:10:47

   --%suite(ut_EMS_TEST_UTIL)
   --%suitepath(alltests)

   --%test
   procedure upload_questions_to_db;

   --%test
   procedure insert_correct_ans;

end ut_EMS_TEST_UTIL;

/
