--------------------------------------------------------
--  DDL for Package UT_EMS_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_EMS_UTIL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-12 11:14:06

   --%suite(test_testems_utiltestpkg)
   --%suitepath(alltests)

   --%test
   procedure delete_institute;

   --%test
   procedure delete_parents;

   --%test
   procedure delete_students;

   --%test
   procedure delete_employee;

   --%test
   procedure issue_book;

   --%test
   procedure return_book;

   --%test
   procedure renew_book;

   --%test
   procedure upload_attendance_to_db;

   --%test
   procedure upload_subjects_to_db;

   --%test
   procedure upload_admission_to_db;

   --%test
   procedure upload_employees_to_db;

   --%test
   procedure upload_ass_subjects_to_db;

   --%test
   procedure hostel_assign_room;

   --%test
   procedure assign_vehicle;

end ut_ems_util;

/
