--------------------------------------------------------
--  DDL for Package UT_OMS_LEAVE_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_LEAVE_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 15:20:27

   --%suite(UT_OMS_LEAVE_UTL)
   --%suitepath(alltests)

   --%test
   procedure process_paid_leave;

   --%test
   procedure process_unpaid_leave;

   --%test
   procedure manage_half_leave;

end UT_OMS_LEAVE_UTL;

/
