--------------------------------------------------------
--  DDL for Package UT_OMS_LOGIN_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_LOGIN_PKG" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 15:06:21

   --%suite(UT_OMS_LOGIN_PKG)
   --%suitepath(alltests)

   --%test
   procedure login;

end UT_OMS_LOGIN_PKG;

/
