--------------------------------------------------------
--  DDL for Package UT_OMS_PROJECT_MANAGE_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_PROJECT_MANAGE_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 15:46:42

   --%suite(UT_OMS_PROJECT_MANAGE_UTL)
   --%suitepath(alltests)

   --%test
   procedure assign_ticket;

   --%test
   procedure delete_ticket;

   --%test
   procedure delete_project;

end UT_OMS_PROJECT_MANAGE_UTL;

/
