--------------------------------------------------------
--  DDL for Package UT_OMS_PRINT_SALARY_SLIP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_PRINT_SALARY_SLIP" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 16:51:28

   --%suite(UT_OMS_PRINT_SALARY_SLIP)
   --%suitepath(alltests)

   --%test
   procedure print_salslip;

end UT_OMS_PRINT_SALARY_SLIP;

/
