--------------------------------------------------------
--  DDL for Package UT_OMS_WORKING_HRS_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_WORKING_HRS_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 16:56:13

   --%suite(UT_OMS_WORKING_HRS_UTL)
   --%suitepath(alltests)

   --%test
   procedure create_working_hrs;

   --%test
   procedure allocate_working_hrs;

   --%test
   procedure create_working_hour_slots;

end UT_OMS_WORKING_HRS_UTL;

/
