--------------------------------------------------------
--  DDL for Package UT_OMS_EMP_UTIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_EMP_UTIL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-27 17:56:45

   --%suite(test_testoms_emp_utltestpkg)
   --%suitepath(alltests)

   --%test
   procedure get_employee_code;

   --%test
   procedure get_emptypecode_fromusername;

   --%test
   procedure get_empid_fromusername;

   --%test
   procedure delete_employee;

   --%test
   procedure upload_emp_file;

   --%test
   procedure upload_empcoll_intable;

end UT_OMS_EMP_UTIL;

/
