--------------------------------------------------------
--  DDL for Package UT_OMS_USER_UTL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "INSTITUTE"."UT_OMS_USER_UTL" is

   -- generated by utPLSQL for SQL Developer on 2023-04-28 14:59:03

   --%suite(UT_OMS_USER_UTL)
   --%suitepath(alltests)

   --%test
   procedure get_usertypecode_fromusername;

   --%test
   procedure get_compid_fromusername;

   --%test
   procedure get_userid_fromusername;

   --%test
   procedure create_user_types;

end UT_OMS_USER_UTL;

/
